apiVersion: apps/v1
kind: Deployment
metadata: 
   name: myefs
spec:
   selector:
     matchLabels:
       app: efs-provisioner
   replicas: 1
   strategy:
     type: Recreate
   template:
     metadata:
       labels:
         app: efs-provisioner
     spec:
       containers:
         - name: efs-provisioner
           image: quay.io/external_storage/efs-provisioner:v0.1.0
           env:
             - name: FILE_SYSTEM_ID
               value: fs-93ce4442
             - name: AWS_REGION
               value: ap-south-1
             - name: PROVISIONER_NAME
               value: cloud/aws-efs
           volumeMounts:
             - name: pv-volume
               mountPath: /persistentvolumes
       volumes:
         - name: pv-volume
           nfs: 
             server: fs-93ce4442.efs.ap-south-1.amazonaws.com
             path: /