apiVersion: v1
kind: Service
metadata:
  name: owncloud
  labels:
    app: owncloud
spec:
  ports:
    - port: 80
  selector:
    app: owncloud
    tier: frontend
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: "aws-efs"
  labels:
    app: owncloud
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1

kind: PersistentVolume

metadata:
  name: wp-pv-claim
  labels:
    app: owncloud
  annotations:
    volume.beta.kubernetes.io/storage-class: "aws-efs"


spec:
  storageClassName: "aws-efs"
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  nfs:
    server: fs-93ce4442.efs.ap-south-1.amazonaws.com
    path: /
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: owncloud
  labels:
    app: owncloud
spec:
  selector:
    matchLabels:
      app: owncloud
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: owncloud
        tier: frontend
    spec:
      containers:
      - image: owncloud:10.0.10-apache
        name: owncloud
        env:
        - name: OWNCLOUD_DB_HOST
          value: owncloud-mysql
        - name: OWNCLOUD_DB_PASSWORD
          value: nilesh@123
        ports:
        - containerPort: 80
          name: owncloud
        volumeMounts:
        - name: owncloud-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: owncloud-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim